name: Continuous Integration Workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Run the linter to check for code style issues
  lint:
    name: 'Run linter'
    defaults:
      run:
        shell: bash
        # Define the working directory for all run steps in the workflow
        working-directory: ./web
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v3
      name: 'Checkout repository'
    
    - name: 'Install Dependencies'
      run: |
        npm install
        npm install --prefix ./Rabbit-MQ

    - name: 'Run Linter'
      run: npm run lint-check

    # Run the prettier to check for code format issues
  code-format:
    name: 'Run prettier'
    defaults:
      run:
        shell: bash
        # Define the working directory for all run steps in the workflow
        working-directory: ./web
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v3
      name: 'Checkout repository'
    
    - name: 'Install Dependencies'
      run: |
        npm install
        npm install --prefix ./Rabbit-MQ

    - name: 'Run Linter'
      run: npm run format-check

  # Run unit tests to make sure everything is 👍
  test:
    name: 'Run unit tests'
    defaults:
      run:
        shell: bash
    # Specify the OS we want the workflow to run on
    runs-on: ubuntu-latest
    # Define the steps for this job
    steps:
    - uses: actions/checkout@v3
      name: 'Checkout repository'

    - name: 'Install Dependencies'
      run: |
        npm install
        npm install --prefix ./Rabbit-MQ
        npm run build
    
    - name: 'Run Tests'
      run: npm run test

