name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update FOMS Code
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          script: |
            cd Food-Order-Management-System
            git pull
            cd ~
            echo 'Deployment successful to digital ocean'
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.0.00
      - name: Install Dependencies and Build React App
        run: |
          pwd
          ls -la
          npm ci
          npm run build
      # - run: npm --prefix ~/Food-Order-Management-System run build
      # - run: pm2 restart foms
